import Head from "next/head"
import { BsFillMoonStarsFill } from "react-icons/bs"
import Image from "next/image"
import { useState } from "react"
//import deved from '../public/img.png'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  console.log(darkMode)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dulea Iustina Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className=" bg-amber-500  h-screen flex justify-between p-10  dark:bg-gray-600">
          <BsFillMoonStarsFill
            className=" bg-white text-6xl rounded-full"
            onClick={() => setDarkMode(!darkMode)}
          />
          <h2 className=" font-bold h-20 text-7xl shadow-lg">Hello</h2>
        </section>
        <div
          className="flex flex-col lg:flex-row"
          width={"100%"}
          layout="responsive"
        >
          <li className=" basis-1/2">1</li>
          <li className=" basis-1/2 flex-1">2</li>
        </div>
      </main>
    </div>
  )
}
